version: '3.8'

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3

  # Object Storage
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO bucket creation
  minio-buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 admin password123; do
        echo 'Waiting for MinIO to be ready...'
        sleep 2
      done;
      /usr/bin/mc mb myminio/raw-videos --ignore-existing;
      /usr/bin/mc mb myminio/processed-videos --ignore-existing;
      echo 'Buckets created successfully';
      exit 0;
      "

  # AudioRemoval Worker
  audio-removal:
    build: ./Workers/AudioRemoval
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672/
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - RAW_BUCKET=raw-videos
      - PROCESSED_BUCKET=processed-videos
      - QUEUE_NAME=audio_removal_queue
    restart: unless-stopped

volumes:
  rabbitmq_data:
  minio_data: